### ISSUE TITLE
[⭐️ TIP] : viewDidLoad() 에 관하여

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#12]
## 작업내용
- [x] 쑤가 viewDidLoad()에 관하여 여쭤보셔서 한번 알아보도록 하겠습니다.

## 스크린샷 
- <img width="375" alt="image" src="https://user-images.githubusercontent.com/103012763/178857460-d7c288fa-e83b-464d-8b3d-24c4675e07b1.png">

## Reference
- 레퍼런스는 해당 코멘트에다가 첨부할게요!(혹은 최종적으로 여기다가 다시 한번 쭉 모아서 정리할수도 있고요)

**Comment by GroundDev** [comment]
> viewDidLoad()에 관한 공식문서입니다.
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621495-viewdidload

> Called after the controller's view is loaded into memory.

해당 컨트롤러의 뷰가 load 되고 난 후에 호출되는 함수라고 하네요.

> You usually override this method to perform additional initialization on views that were loaded from nib files.

뷰에 추가적인 초기화가 필요할 경우 이 함수를 이용하게 된다고 하네요.

**Comment by SeonJeon** [comment]
> > viewDidLoad()에 관한 공식문서입니다.
> > https://developer.apple.com/documentation/uikit/uiviewcontroller/1621495-viewdidload
> 
> > Called after the controller's view is loaded into memory.
> 
> 해당 컨트롤러의 뷰가 load 되고 난 후에 호출되는 함수라고 하네요.
> 
> > You usually override this method to perform additional initialization on views that were loaded from nib files.
> 
> 뷰에 추가적인 초기화가 필요할 경우 이 함수를 이용하게 된다고 하네요.

그래서 지우면 어떻게 되나요...?

**Comment by GroundDev** [comment]
이 `viewDidLoad()`함수에 대해 알아볼려면 우선 ViewController의 Life Cycle이란 개념에 대해 학습해야할 것으로 보입니다.
우선 잘 정리되어있는 블로그 글을 첨부할게요! 내용은 차근차근 정리해봅시다.
https://inuplace.tistory.com/1080?category=1034353
