### ISSUE TITLE
[⭐️ TIP] : Swift 함수에 관하여

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#14]
## 작업내용
- [x] Swift 문법에서의 함수에 관하여 정리해보겠습니다.

## 스크린샷 
- UI 작업은 없습니다.

## Reference
- 최종적으로 정리해서 여기에 올리겠습니다.

**Comment by GroundDev** [comment]
함수란 무엇인가?에 대한 답은 구글링을 서치함으로써 상당부분 얻을 수 있을 것으로 보입니다.
저는 그 중에서도 클로져에 대해 정리를 해보도록 하겠습니다.
다만, 이 내용은 저의 뇌에서 근거없이 술술 나오는 내용이니, 너무 신빙성 있는 자료로 삼지는 않으셨으면 좋겠습니다.
그럼, 시작하죠.

옛날 옛적 어느날 컴퓨터 천재분들이 기존의 언어에 학을 떼며 연구를 매진하다 WWDC 2014에서 스위프트라는 새로운 언어를 발표하기에 이릅니다.
기존의 언어보다 더욱 빠르고 안전하다는 특성을 갖고 있는 이 스위프트는 기존의 언어에서는 찾을 수 없었던 몇가지 새로운 syntax가 있습니다.
이러한 syntax들에는 옵셔널, 클로져 등등이 있겠습니다.
다른 언어들도 얕고 좁게 공부했던 저는 이러한 개념들이 정말 신기했습니다.
특히 옵셔널! 어떠한 변수에 있을수도 있고 없을수도 있음을 암시하는 선언 방식이 독특했습니다.
한가지 더 특이했던 건 바로 클로져입니다.

클로져란 무엇일까요? 익명함수입니다. 그럼 '익명'이 아닌 함수가 있단 걸까요? 네 기존에 저희가 알고 있던 함수가 그러한 '익명'이 **아닌** 함수입니다. 사실 엄밀히 말하자면 함수 또한 클로져의 범주에 속합니다. 즉, 클로져 안에는 저희가 기존에 알고 있던 형태인 함수(익명이 아닌 함수의 꼴)와 클로져(익명인 함수의 꼴)이 존재하는 것이죠. 그래서 문맥에 따라서 클로져라 함은 이렇게 함수와 익명함수를 통칭해서 부르기도 하고, 어떤 경우에는 단순히 함수와 대비되는 익명함수를 지칭하기도 합니다. 보통의 경우에는 후자의 경우로 많이 쓰이긴 합니다. 즉, 우리가 흔히 봐 왔던 함수가 있고, 그러한 함수와는 달리 '익명'인 함수는 클로져라고 지칭하는 것이죠.
그렇다면 컴퓨터 천재분들은 뭣하러 이러한 클로져(익명함수)란 개념을 만든 걸까요?




클로져란? 익명함수입니다.

**Comment by GroundDev** [comment]
위와 같은 클로져는 어떠한 함수의 인자로 전달될 수 있습니다.
가령 `( ) -> Void`꼴인 클로져를 인자로 받을려는 함수 `tossChangedValue(currentValue:determine:)`가 있다고 할게요.
```Swift
func tossChangedValue(currentValue: Int, determine: (Bool) -> Void) -> Void {
    // function의 body 부분입니다.
}
```
즉, determine이라는 파라미터에 전달되는 인자로는 아무것도 받지 않고 아무것도 반환하지 않는 형태를 갖고 있는 클로져가 오기를 원한다고 하네요.
그렇다면 그냥 그런 조건에 맞는 클로져를 전달해주면 됩니다.
근데 이때 함수의 마지막 인자로 전달되는 클로져 같은 경우엔 다음과 같이 좀 더 간편한 형태를 취할 수 있습니다. 이를 후행 클로져라고 해요.
```Swift
tossChangedValue(currentValue: Int, determine : {
    // determine에 들어가는 클로져의 body 부분입니다.
})
```
```Swift
tossChangedValue(currentValue: Int) {
    // determine의 위치에 들어가는 클로져의 body 부분입니다.
}
```

근데 살짝 바꿔봅시다. 저희가 위에서 언급했던 `chooseWhichFunction(isIncrement:)`함수를 활용해보고 싶어요. 이 녀석이 두번째 인자로 들어가게 만들어보겠습니다.
```Swift
func tossChangedValue(currentValue: Int, determine: (Bool) -> (Int) -> Int) -> Int {
    determine(currentValue > 0)(currentValue)
}
```
```Swift
let newValue = tossChangedValue(currentValue : -4, determine: { }
```

**Comment by GroundDev** [comment]
참고로 위에는 논리오류가 있습니다. 뭐냐고요? 만일 currentValue로 0이 전달될 경우에는 가만히 있어야 하잖아요? 0을 향해 가는게 우리의 프로젝트의 목적이니까요. 그런데 해보시면 아시겠지만 1이 생성됩니다. 이러한 논리 오류를 여기선 수정하진 않겠습니다. 중요한 건 클로져의 syntax를 살펴보는거니까요. 그러나 실제로 프로젝트에 임하실때는 이러한 논리오류가 발생하지 않는지 면밀히 살펴보는게 필요하겠습니다.
긴 글 읽어주셔서 대단히 감사합니다!

**Comment by GroundDev** [comment]
언제나 물어보십쇼 한스!
제가 아는 내용이라면 최대한 쉽게 설명해드릴려고 노력할테고
그렇지 않다면 공부해와서 설명드리겠습니다

**Comment by 22Seongsoo** [comment]
처음에 함수 코드보고 뒤로가기 누를 뻔 했는데 다 읽고 나니까 왜 클로저를 쓰는지 알겠어요. 저런 깔끔한 코드를 보면 사람들이 뒤로가기를 안 누를 것 같아요.
몰랐던 내용인데 정리해주셔서 고맙습니다😀

**Comment by SeonJeon** [comment]
클로져가 머리로는 이해가 되는데 막상 쓰려면 진짜 헷갈리더라구요
단계별로 정리를 너무 잘하셨네요 좋은 정보 감사합니다 :)
