### ISSUE TITLE
[✨ FEAT] : LoginGiverView 구현

### ISSUE THREAD

**Issue by 22Seongsoo** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#22]
## 작업내용
- [ ] UILabel, 텍스트필드, 버튼 사용해서 뷰 구현

## 스크린샷 
- UI 작업 시, 스크린샷 첨부
![Login_giver_2](https://user-images.githubusercontent.com/103010751/179351812-97acf399-be51-4ff0-af8d-1a91d3badd9c.png)

## Reference
- AutoLayout 적용하기
https://zeddios.tistory.com/380#recentEntries

**Comment by SeonJeon** [comment]
Figma와 한치의 오차도 없는 레이아웃 👍🏻
