### ISSUE TITLE
[✅ ADD] : CloudKit 세팅

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#26]
## 작업내용
- [x] CloudKit 환경설정을 완료합니다.
- [x] CloudKit을 프로젝트 내에서 사용 가능하도록 만듭니다.

## 스크린샷 
스크린샷은 없을 예정입니다.

## Reference
레퍼런스는 그때그때 올릴게요

**Comment by GroundDev** [comment]
시작하기에 앞서, CloudKit의 개념에 관해 아주아주 심플하게 정리해둔 이슈가 있으니 해당 이슈를 참고하시면 이해하는데에 도움이 되리라 생각합니다( #3 )

**Comment by GroundDev** [comment]
https://www.raulferrergarcia.com/en/develop-a-todo-app-with-cloudkit/

**Comment by GroundDev** [comment]
https://ios-development.tistory.com/812?category=899471
<img width="671" alt="image" src="https://user-images.githubusercontent.com/103012763/179399811-7b68c1d8-8659-41af-8b1c-de3cee802737.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/103012763/179399844-496a7da6-841a-4376-9fc0-78c4aa1ba0bc.png">
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/103012763/179399900-34479913-be05-43fb-9ebd-6efec82f88f4.png">
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/103012763/179399942-ef1927b8-b525-4b82-baa1-7dbfe5e38892.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/103012763/179399999-3ba01a2a-7e78-4e9b-a581-4f50f08ab56c.png">

https://www.raywenderlich.com/4878052-cloudkit-tutorial-getting-started

**Comment by GroundDev** [comment]
늘 그렇듯이 하긴 했는데 제대로 될련지는 모르겠습니다ㅋㅋㅋㅋㅋㅋㅋ
<img width="873" alt="image" src="https://user-images.githubusercontent.com/103012763/179401043-6fcf187e-882a-4747-8162-9970bb097b3f.png">

**Comment by GroundDev** [comment]
단, 팀 내의 다른 인원이 이 앱을 빌드할 때 Team명이 다를텐데 이 때문에 문제가 생길지는 잘 모르겠습니다.
그래서 일단 PR 및 Merge는 하지 않도록 하겠습니다.

**Comment by GroundDev** [comment]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/103012763/179401767-10691b97-fbc1-4706-8bd1-53562477671c.png">

**Comment by GroundDev** [comment]
## Feedback
이 record type은 위탁가정측을 나타내는 데이터입니다.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/103012763/179403416-81796ce1-a022-42f9-b812-0fc5ecf77033.png">
message, photo 두 가지의 데이터 타입을 가집니다. 어차피 누가 보냈는지는 식별하지 않으므로 userName같은 데이터는 없습니다.
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/103012763/179403448-28d7c322-7211-4b96-91b9-0791b684387b.png">
sample 자료로 두 건의 피드백이 있으며, 그 중 하나는 사진이 있는 형식으로 만들어놨습니다.

**Comment by SeonJeon** [comment]
> 단, 팀 내의 다른 인원이 이 앱을 빌드할 때 Team명이 다를텐데 이 때문에 문제가 생길지는 잘 모르겠습니다. 그래서 일단 PR 및 Merge는 하지 않도록 하겠습니다.

우려하던 일이 일어났습니다 두둥
