### ISSUE TITLE
[✏️ CORRECT] : 도피가 쏘아올린 작은 공(class 내의 let property에 관하여)

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#37]
## 작업내용
- [x] 도피의 코드리뷰 내용을 반영하기 위해 끙끙대보다가 이해되지 않는 부분이 있어 올립니다. [#29 comment](https://github.com/DeveloperAcademy-POSTECH/MC3-Team11-DBAL/pull/29#discussion_r923237306)
- 작업 상황은 다음과 같이 진행중입니다.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/103012763/179504100-5996db2d-3e99-44f1-8739-3a4d7a4b46bc.png">
위와 같이 초기화 순서로 인해 문제가 생겼습니다.
- 이에 혹시나 해서 static으로 선언해 봤습니다.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/103012763/179504213-fd3c18ec-284c-49da-9a51-0856e0fe709c.png">
그랬더니 띠용 오류가 생기지 않는 겁니다.
- 이게 대체 왜 이렇게 된거지? 클래스 내에서 static으로 선언하게 되면 해당 인스턴스를 생성하기 전에 이미 생성이 되어있는건가?
싶어서 관련된 내용들을 좀 찾아봤는데, 오히려 그 반대로 lazy하게 선언된다는 점을(?) 알게 되었습니다.
- 이에 관해 얘기를 나눠보고 싶어 이슈를 열게 되었습니다.

## 스크린샷 
- UI 관련 작업은 아닙니다.

## Reference
- 레퍼런스는 그때그때 올리겠습니다.

**Comment by ddophi98** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/72330884/179647784-9fc4837c-2a3e-4212-a425-56f2ad9c7c71.png">


저런 오류가 이렇게 약간 초기화가 안된 상태에서 다른 변수에 할당하려할떄? 생기긴합니다

**Comment by ddophi98** [comment]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/72330884/179647859-9e34fb51-2573-4adf-a5d0-b6588c06b13d.png">

그래서 저는 주로 저 오류 해결할땐 이렇게 쓰죠

**Comment by GroundDev** [comment]
감사합니다!
