### ISSUE TITLE
[⭐️ TIP] : 7월25일부터는 develop 브랜치에서 새로 브랜치 생성해주세요

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#52]
## 작업내용
- [x] 도피가 열심히 sprint1과 추가 변경사항들을 모두 develop브랜치로 합쳐놓아주셨습니다(#44, #46, #48)
- [x] 이후 오늘부로(7월25일) 작업하실때는 아래와 같은 flow로 작업하시면 됩니다.

- 2차 스프린트 백로그를 들어가봅니다. 
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/103012763/180730442-97915580-4de3-4b3a-ad7c-b48c4c0aa251.png">

- 작업하실려는 항목을 살펴봅니다.
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/103012763/180731165-6bf94e61-27b9-42a2-acb2-118561348ad3.png">

- 이슈를 만듭니다.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/103012763/180731848-ee3dd80d-9383-4fc6-86cd-48b27514db1a.png">

- 방금 생성한 이슈의 번호가 무엇인지 확인합니다. 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/103012763/180732055-8c6f7831-e264-46bd-ad6f-03ac2b4d9b4b.png">

- 이슈번호를 업데이트합니다. 담당자 또한 자신으로 지정하고, 진행도 사항을 업데이트해줍니다(`in progress`)
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/103012763/180732151-8588d25e-7905-4794-8697-57f1c0e36fc6.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/103012763/180732361-fa24844f-f71a-4965-8af6-1d11ae15a179.png">

- 이후 브랜치를 생성하여 작업을 진행하시고, 깃헙으로 push 하신 후에 PR을 날려서 팀원분들께 공유해주시면 됩니다.
- 만일 중간에 잘 모르겠는 부분이 생긴다면 issue에서 question template을 활용하시거나, 코드를 좀 같이 살펴봐줬으면 한다면 PR을 draft방식으로 올리는 방법도 있겠습니다.

## Reference
- [노션 2차 스프린트 백로그](https://dbal2.notion.site/2-b01fd31cedac4af7a7b460b8a795f0c4)

**Comment by GroundDev** [comment]
만일, 작업을 진행할려는데 기존의 백로그에는 쓰여있지 않은 작업을 진행하고자 하실 경우엔
간단합니다 백로그에 해당 작업을 추가하고 위의 flow를 진행하시면 됩니다.

**Comment by 22Seongsoo** [comment]
넵 확인했습니다!
정리해주셔서 고마워요 :)
