### ISSUE TITLE
[⭐️ TIP] : Good Bye, CloudKit

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#82]
## 작업내용
- [x] 술 한잔 마셨습니다...
- CloudKit을 이용하여 앱을 구현하게 되면, 하나의 앱에는 통상 하나의 container가 위치하게 됩니다.
- 이때 그 container는 해당 container를 생성한 계정에 종속되게 됩니다.
- 따라서 다른 이들은 이 container에 접근할 권한이 없습니다.
- 해결방법은 두 가지입니다.
- 첫번째는, 팀 계정으로 provisioning profile을 만들어서 이 profile을 통해 팀의 명의로 container를 생성하는 방식이 있는데, 저희가 갖고 있는 계정은 모두 개인 계정입니다.
- 팀 계정으로 변경하는 방법이 없지는 않으나 이는 기업이나 법인임을 증명하는 과정을 동반합니다.
- 두번째는, 인증서를 개발용이 아니라 배포용으로 받는 방법이 있습니다. 이 경우 특정 기기에 상관없이 모든 기기가 이 앱을 다운받아서 쓸 수 있습니다. **단, App Store 심사를 통과해야합니다**. 통과 전까지는 단 한대의 기기에서도 테스트해볼 수 없습니다. 그러니까 배포용이죠.
- 이에 아직 애플 측으로부터 답변을 얻은 건 아니나, CloudKit은 저희 팀 프로젝트로는 이용할 수 없는 기술인 것으로 보입니다.

## 노션 정리
https://groundkjs.notion.site/7-28-CloudKit-provisioning-profile-a4d16a7bfc7e432c8ec7205b5a2803bc

## 대안
Firebase를 공부해서 구현해보겠습니다.

**Comment by GroundDev** [comment]
https://stackoverflow.com/questions/26732251/how-to-remove-provisioning-profiles-from-xcode
CloudKit 관련한 provisioning profile을 제거하는 방법은 위와 같습니다.
우선은 Firebase를 어떻게 사용할 것인지를 공부한 뒤에 CloudKit 관련된 것들을 하나하나 지워나가겠습니다.

**Comment by 22Seongsoo** [comment]
잘가 클킷,,
