### ISSUE TITLE
[⭐️ TIP] : Welcome, Firebase

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#84]
## 작업내용
- [x] #82 에서 봤듯이, 저희 서버는 CloudKit으로 구현할 수 없는 상황입니다.
- [x] 이에 대안으로 FireBase를 이용해서 구현해보겠습니다.

## Reference
- 레퍼런스는 그때그때

**Comment by HANS5109** [comment]
가보자고 🔥🐻

**Comment by HANS5109** [comment]
화이팅입니다

**Comment by GroundDev** [comment]
Firebase에 관해 공부하는 내용은 아래 노션에 정리하겠습니다.
https://groundkjs.notion.site/7-28-Firebase-cf68a2ce7e3a40508b96d5179a012df5

**Comment by HANS5109** [comment]
좋읍니다~!!👍
