### ISSUE TITLE
[✅ ADD] 프로젝트 생성 및 파일 추가

### ISSUE THREAD

**Issue by ddophi98** [DeveloperAcademy-POSTECH/MC3-Team11-DBAL#9]
## 작업내용
- [ ] 프로젝트 생성
- [ ] storyboard 파일 추가 (뷰 단위로 쪼개기)

## Reference
- https://silver-g-0114.tistory.com/36

**Comment by GroundDev** [comment]
## Q) 도피는 왜 뷰 단위로 스토리보드를 만드는 것일까요?
### A) 스토리보드 관련 conflict 예방
오늘 세션시간때 영이 이 스토리보드 관련해서 conflict이 발생하는 상황이 있는데, 그걸 미리 예방할 수 있는 방법들이 있다고 힌트를 주셨어요.
https://beepeach.tistory.com/611?category=912549
위의 reference를 비롯해서, 조금 찾아보니
한 뷰당 스토리보드 하나
로 대응하게 되면 그래도 conflict이 날 가능성을 줄일 수 있다고는 합니다.
다만 이렇게 하면 전체 뷰의 흐름을 한눈에 볼 수 없다는 단점은 있다고 해요.

또한, 스토리보드가 정말 골때리는게 실행만 해도 변경사항이 생기는 경우가 있다네요(ㅋㅋㅋㅋㅋㅋㅋㅋ)
그래서  `.gitignore`에 `*.xcuserstate`를 추가시키는 작업이 필요할 것으로 보입니다.
